[build]
builder = "nixpacks"

[deploy]
startCommand = "./turn-server"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[deploy.exposedPorts]]
port = 3478
protocol = "udp"
